### ISSUE TITLE
Happycache load inefficient for machines with many cores

### ISSUE THREAD

**Issue by jolynch** [hashbrowncipher/happycache#5]
It appears that by default happycache chooses 8*cores threads to do loading, but on machines with 32+ cores this leads to a lot of contention on the shared work queue and slows us down in production.

We've implemented a hotfix that just halves the number of threads that happycache uses via the command line but I believe that @hashbrowncipher has plans for a less lockful path to loading which would remove the need for that hack.

**Comment by hashbrowncipher** [comment]
I believe this is fixed by #6. Your review there is welcome.

**Comment by hashbrowncipher** [comment]
Yes, this is fixed.
